sudo: required
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version

services:
  - docker

before_script:
  - docker swarm init
  - docker node ls
  - chmod +x *.sh

script:
  - ./deployStack.Vagrant.sh
  - sleep 120 #wait for the stack to come up

after_script:
  - docker stack services ci
  - docker stack ps ci
  - ./removeStack.sh
